redis = "12800"

[train]
resume = false
epoch = 10
output_dir = "./outputs/phi4-14b-p-fsdp4-r-tp2-grpo"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 1e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.999,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 384
sync_weight_interval = 1

[rollout]
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
n_generation = 16
batch_size = 24
quantization = "none"
max_response_length = 1024


[policy]
model_name_or_path = "microsoft/phi-4"
model_max_length = 1024
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_rl"
experiment_name = "None"

[train.train_policy]
type = "grpo"
dataset.name = "openai/gsm8k"
dataset.subset = "main"
dataset.split = "train"
prompt_column_name = "question"
response_column_name = "answer"
reward_function = "gsm8k"
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 8

[train.ckpt]
enable_checkpoint = true
save_freq = 100
save_mode = "async"

[rollout.parallelism]
n_init_replicas = 4
tp_size = 2
pp_size = 1

[rollout.sampling_config]
temperature = 0.9
top_p = 1.0
top_k = 10

[policy.parallelism]
n_init_replicas = 2
tp_size = 1
cp_size = 1
dp_shard_size = 4
pp_size = 1
dp_replicate_size = 1
